import './globals.css'
import { Inter } from 'next/font/google'
import { RewardProvider } from '@/contexts/RewardContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`${inter.className} bg-dark-primary text-gray-100`}>
        <RewardProvider>
          {children}
        </RewardProvider>
      </body>
    </html>
  )
}
